import type { User, WasteLog, PickupRequest, ActivityLog, Transport, Notification } from "./_types"

/**
 * In-memory data storage for demo/testing purposes.
 * In a real application, this would be replaced with database queries.
 * 
 * Users are identified by the x-user-id header sent from the frontend.
 */
export const users: User[] = [
  {
    id: "u-admin-1",
    name: "Alice Admin",
    email: "alice@greencafe.com",
    passwordHash: "password", // Note: In production, passwords should be hashed
    role: "admin",
    organizationName: "Green Café",
    cafeId: "cafe-1",
  },
  {
    id: "u-staff-1",
    name: "Sam Staff",
    email: "sam@greencafe.com",
    passwordHash: "password",
    role: "staff",
    organizationName: "Green Café",
    cafeId: "cafe-1",
  },
  {
    id: "u-charity-1",
    name: "Charlie Charity",
    email: "charity@help.org",
    passwordHash: "password",
    role: "charity",
    organizationName: "Hope Charity",
    cafeId: null,
  },
  {
    id: "u-farmer-1",
    name: "Fiona Farmer",
    email: "farm@soil.com",
    passwordHash: "password",
    role: "farmer",
    organizationName: "Soil & Co",
    cafeId: null,
  },
]

export const wasteLogs: WasteLog[] = [
  {
    id: "w1",
    cafeId: "cafe-1",
    type: "edible",
    itemName: "Pastries",
    quantity: 15,
    expiryDate: "2025-12-05",
    status: "pending",
    assignedTo: "charity",
    createdAt: "2025-12-01T08:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "w2",
    cafeId: "cafe-1",
    type: "organic",
    itemName: "Vegetable Scraps",
    quantity: 22,
    expiryDate: "2025-12-04",
    status: "pending",
    assignedTo: "farmer",
    createdAt: "2025-12-01T09:00:00Z",
    updatedAt: "2025-12-01T09:00:00Z",
  },
  {
    id: "w3",
    cafeId: "cafe-1",
    type: "coffee",
    itemName: "Coffee Grounds",
    quantity: 10,
    expiryDate: "2025-12-03",
    status: "collected",
    assignedTo: "farmer",
    createdAt: "2025-11-30T10:00:00Z",
    updatedAt: "2025-12-01T10:00:00Z",
  },
  {
    id: "w4",
    cafeId: "cafe-1",
    type: "edible",
    itemName: "Sandwiches",
    quantity: 8,
    expiryDate: "2025-12-02",
    status: "dropped",
    assignedTo: "charity",
    createdAt: "2025-11-30T11:00:00Z",
    updatedAt: "2025-12-01T11:00:00Z",
  },
  // Add more available items for charity
  {
    id: "w5",
    cafeId: "cafe-1",
    type: "edible",
    itemName: "Fresh Bread",
    quantity: 12,
    expiryDate: "2025-12-10",
    status: "pending",
    assignedTo: "charity",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "w6",
    cafeId: "cafe-1",
    type: "edible",
    itemName: "Muffins & Croissants",
    quantity: 20,
    expiryDate: "2025-12-08",
    status: "pending",
    assignedTo: "charity",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Add more available items for farmer
  {
    id: "w7",
    cafeId: "cafe-1",
    type: "organic",
    itemName: "Fruit Peels",
    quantity: 15,
    expiryDate: "2025-12-09",
    status: "pending",
    assignedTo: "farmer",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "w8",
    cafeId: "cafe-1",
    type: "coffee",
    itemName: "Used Coffee Grounds",
    quantity: 18,
    expiryDate: "2025-12-07",
    status: "pending",
    assignedTo: "farmer",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Add NEW farmer items WITHOUT pickup requests (these will be available)
  {
    id: "w9",
    cafeId: "cafe-1",
    type: "organic",
    itemName: "Banana Peels",
    quantity: 25,
    expiryDate: "2025-12-20",
    status: "pending",
    assignedTo: "farmer",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "w10",
    cafeId: "cafe-1",
    type: "coffee",
    itemName: "Fresh Coffee Grounds",
    quantity: 30,
    expiryDate: "2025-12-18",
    status: "pending",
    assignedTo: "farmer",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "w11",
    cafeId: "cafe-1",
    type: "organic",
    itemName: "Vegetable Waste",
    quantity: 35,
    expiryDate: "2025-12-25",
    status: "pending",
    assignedTo: "farmer",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Add NEW charity items WITHOUT pickup requests (these will be available)
  {
    id: "w12",
    cafeId: "cafe-1",
    type: "edible",
    itemName: "Fresh Sandwiches",
    quantity: 18,
    expiryDate: "2025-12-20",
    status: "pending",
    assignedTo: "charity",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "w13",
    cafeId: "cafe-1",
    type: "edible",
    itemName: "Day-Old Pastries",
    quantity: 22,
    expiryDate: "2025-12-19",
    status: "pending",
    assignedTo: "charity",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "w14",
    cafeId: "cafe-1",
    type: "edible",
    itemName: "Leftover Meals",
    quantity: 15,
    expiryDate: "2025-12-22",
    status: "pending",
    assignedTo: "charity",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const pickupRequests: PickupRequest[] = [
  {
    id: "p1",
    wasteId: "w1",
    requesterId: "u-charity-1",
    requesterType: "charity",
    requestedAt: "2025-12-01T12:00:00Z",
    status: "pending",
    preferredTime: "Morning",
  },
  {
    id: "p2",
    wasteId: "w2",
    requesterId: "u-farmer-1",
    requesterType: "farmer",
    requestedAt: "2025-12-01T13:00:00Z",
    status: "approved",
  },
  {
    id: "p3",
    wasteId: "w3",
    requesterId: "u-farmer-1",
    requesterType: "farmer",
    requestedAt: "2025-11-30T13:00:00Z",
    status: "collected",
  },
  // Add approved charity request
  {
    id: "p4",
    wasteId: "w5",
    requesterId: "u-charity-1",
    requesterType: "charity",
    requestedAt: new Date().toISOString(),
    status: "approved",
    notes: "Please pack in boxes",
  },
  // Add another approved charity request
  {
    id: "p5",
    wasteId: "w6",
    requesterId: "u-charity-1",
    requesterType: "charity",
    requestedAt: new Date().toISOString(),
    status: "approved",
  },
  // Add approved farmer request
  {
    id: "p6",
    wasteId: "w7",
    requesterId: "u-farmer-1",
    requesterType: "farmer",
    requestedAt: new Date().toISOString(),
    status: "approved",
  },
  // Add another approved farmer request
  {
    id: "p7",
    wasteId: "w8",
    requesterId: "u-farmer-1",
    requesterType: "farmer",
    requestedAt: new Date().toISOString(),
    status: "approved",
  },
]

export const activityLogs: ActivityLog[] = [
  {
    id: "a1",
    userId: "u-staff-1",
    actionType: "logged",
    itemName: "Pastries",
    createdAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "a2",
    userId: "u-charity-1",
    actionType: "donationRequested",
    itemName: "Pastries",
    createdAt: "2025-12-01T12:05:00Z",
  },
  {
    id: "a3",
    userId: "u-farmer-1",
    actionType: "farmRequest",
    itemName: "Vegetable Scraps",
    createdAt: "2025-12-01T13:05:00Z",
  },
  {
    id: "a4",
    userId: "u-admin-1",
    actionType: "dropped",
    itemName: "Sandwiches",
    createdAt: "2025-12-01T14:00:00Z",
  },
]

export const transports: Transport[] = []

export const notifications: Notification[] = []

